const deck = [
    { name: 'Ace of Hearts', value: 14, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Playing_card_heart_A.svg/195px-Playing_card_heart_A.svg.png' },
    { name: '2 of Hearts', value: 2, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/English_pattern_2_of_hearts.svg/540px-English_pattern_2_of_hearts.svg.png' },
    { name: '3 of Hearts', value: 3, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Playing_card_heart_3.svg/300px-Playing_card_heart_3.svg.png' },
    { name: '4 of Hearts', value: 4, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/4_of_hearts.svg/1200px-4_of_hearts.svg.png' },
    { name: '5 of Hearts', value: 5, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Playing_card_heart_5.svg/1638px-Playing_card_heart_5.svg.png' },
    { name: '6 of Hearts', value: 6, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Playing_card_heart_6.svg/1200px-Playing_card_heart_6.svg.png' },
    { name: '7 of Hearts', value: 7, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Playing_card_heart_7.svg/819px-Playing_card_heart_7.svg.png' },
    { name: '8 of Hearts', value: 8, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Playing_card_heart_8.svg/1200px-Playing_card_heart_8.svg.png' },
    { name: '9 of Hearts', value: 9, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Playing_card_heart_9.svg/200px-Playing_card_heart_9.svg.png' },
    { name: '10 of Hearts', value: 10, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/10_of_hearts.svg/706px-10_of_hearts.svg.png' },
    { name: 'Jack of Hearts', value: 11, imageUrl: 'https://i.pinimg.com/564x/4d/2b/64/4d2b64c4d80126b47c5d7f38f6cb9aac.jpg' },
    { name: 'Queen of Hearts', value: 12, imageUrl: 'https://i.pinimg.com/736x/ae/0a/e6/ae0ae65bacdf7b8ae357b2340e0c2aca.jpg' },
    { name: 'King of Hearts', value: 13, imageUrl: 'https://m.media-amazon.com/images/I/71d4LRYo6uL._AC_UF1000,1000_QL80_.jpg' },
    
    
    { name: 'Ace of Diamonds', value: 14, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Ace_of_diamonds.svg/1200px-Ace_of_diamonds.svg.png' },
    { name: '2 of Diamonds', value: 2, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/2_of_diamonds.svg/530px-2_of_diamonds.svg.png' },
    { name: '3 of Diamonds', value: 3, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Playing_card_diamond_3.svg/1638px-Playing_card_diamond_3.svg.png' },
    { name: '4 of Diamonds', value: 4, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Playing_card_diamond_4.svg/819px-Playing_card_diamond_4.svg.png' },
    { name: '5 of Diamonds', value: 5, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Playing_card_diamond_5.svg/1200px-Playing_card_diamond_5.svg.png' },
    { name: '6 of Diamonds', value: 6, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/6_of_diamonds.svg/706px-6_of_diamonds.svg.png' },
    { name: '7 of Diamonds', value: 7, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/cd/Poker-sm-238-7d.png' },
    { name: '8 of Diamonds', value: 8, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Playing_card_diamond_8.svg/1638px-Playing_card_diamond_8.svg.png' },
    { name: '9 of Diamonds', value: 9, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Playing_card_diamond_9.svg/800px-Playing_card_diamond_9.svg.png' },
    { name: '10 of Diamonds', value: 10, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/10_of_diamonds.svg/1200px-10_of_diamonds.svg.png' },
    { name: 'Jack of Diamonds', value: 11, imageUrl: 'https://m.media-amazon.com/images/I/71O1j2XSzqL.jpg' },
    { name: 'Queen of Diamonds', value: 12, imageUrl: 'https://www.itiskismet.com/uploads/8/6/0/4/86046504/published/queen-of-diamonds_3.png' },
    { name: 'King of Diamonds', value: 13, imageUrl: 'https://m.media-amazon.com/images/I/71EkglvyWjL._AC_UF1000,1000_QL80_.jpg' },
   
   
    { name: 'Ace of Clubs', value: 14, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/2_of_clubs.svg/1200px-2_of_clubs.svg.png' },
    { name: '2 of Clubs', value: 2, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/2_of_clubs.svg/1200px-2_of_clubs.svg.png' },
    { name: '3 of Clubs', value: 3, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/3_of_clubs.svg/1200px-3_of_clubs.svg.png' },
    { name: '4 of Clubs', value: 4, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Playing_card_club_4.svg/1200px-Playing_card_club_4.svg.png' },
    { name: '5 of Clubs', value: 5, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/5_of_clubs.svg/1200px-5_of_clubs.svg.png' },
    { name: '6 of Clubs', value: 6, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Playing_card_club_6.svg/1200px-Playing_card_club_6.svg.png' },
    { name: '7 of Clubs', value: 7, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/7_of_clubs.svg/1200px-7_of_clubs.svg.png' },
    { name: '8 of Clubs', value: 8, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/8_of_clubs.svg/706px-8_of_clubs.svg.png' },
    { name: '9 of Clubs', value: 9, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Playing_card_club_9.svg/819px-Playing_card_club_9.svg.png' },
    { name: '10 of Clubs', value: 10, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/10_of_clubs.svg/1200px-10_of_clubs.svg.png' },
    { name: 'Jack of Clubs', value: 11, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/English_pattern_jack_of_clubs.svg/1200px-English_pattern_jack_of_clubs.svg.png' },
    { name: 'Queen of Clubs', value: 12, imageUrl: 'https://img.myloview.com.br/posters/queen-of-clubs-400-535652.jpg' },
    { name: 'King of Clubs', value: 13, imageUrl: 'https://ih1.redbubble.net/image.921155394.8729/flat,750x,075,f-pad,750x1000,f8f8f8.jpg' },
   
   
    { name: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Ace_of_spades.svg/1200px-Ace_of_spades.svg.png', value: 14, imageUrl: 'https://example.com/ace_of_spades.png' },
    { name: '2 of Spades', value: 2, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/2_of_spades.svg/1200px-2_of_spades.svg.png' },
    { name: '3 of Spades', value: 3, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/3_of_spades.svg/1200px-3_of_spades.svg.png' },
    { name: '4 of Spades', value: 4, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Playing_card_spade_4.svg/1638px-Playing_card_spade_4.svg.png' },
    { name: '5 of Spades', value: 5, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Playing_card_spade_5.svg/1200px-Playing_card_spade_5.svg.png' },
    { name: '6 of Spades', value: 6, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Playing_card_spade_6.svg/1638px-Playing_card_spade_6.svg.png' },
    { name: '7 of Spades', value: 7, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Playing_card_spade_7.svg/1200px-Playing_card_spade_7.svg.png' },
    { name: '8 of Spades', value: 8, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/PLAYING_CARD_EIGHT_OF_SPADES.svg/800px-PLAYING_CARD_EIGHT_OF_SPADES.svg.png' },
    { name: '9 of Spades', value: 9, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Playing_card_spade_9.svg/1638px-Playing_card_spade_9.svg.png' },
    { name: '10 of Spades', value: 10, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/10_of_spades.svg/1200px-10_of_spades.svg.png' },
    { name: 'Jack of Spades', value: 11, imageUrl: 'https://www.keen.com/wp-content/uploads/sites/2/2022/08/Jack-of-Spades-Meaning.jpg' },
    { name: 'Queen of Spades', value: 12, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/51_Q_di_picche.jpg/800px-51_Q_di_picche.jpg' },
    { name: 'King of Spades',  value: 13, imageUrl: 'https://i.ebayimg.com/images/g/9bEAAOSwH-9ehtWo/s-l1600.jpg' },

    { name: 'back',  value: 0, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Card_back_01.svg/1200px-Card_back_01.svg.png' },

];
